image:
  repository: artifactory.dagility.com/docker/vdcheckghdev-backend
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: vdcheckghdev-backend-habitat-firstonere.dagility.com
    paths:
    - /
serviceAccount:
  create: false
